name: examui
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cupertino_icons: ^1.0.2
  date_time_format: ^2.0.1
  eva_icons_flutter: ^3.0.0
  flutter:
    sdk: flutter
  flutter_rounded_date_picker: ^2.0.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^1.0.7
  intl: ^0.17.0-nullsafety.2
  percent_indicator: ^4.0.0
  shimmer: ^2.0.0

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
